// Async storage keys woudl be here
export default {
    "USER_INFO": "@USER_INFO",
    "INTOR_SCREEN_VIEWED": "@INTOR_SCREEN_VIEWED",
    "INTOR_SCREEN_VIEWED_CHECK_FOR_OTP": "@INTOR_SCREEN_VIEWED_CHECK_FOR_OTP",
    "PERSIST_USER": "@PERSIST_USER",
    "PERSIST_CART": "@PERSIST_CART",
    "BASE_URL": "@BASE_URL",
    "PERSIST_PREV_ORDERS": "@PERSIST_PREV_ORDERS",
}